
CREATE TABLE [COMPRA_RENTA]
(
	[NUMERO_EVENTO] uniqueidentifier NOT NULL,
	[CODIGO_LIBRO] int NOT NULL,
	[ID_ESTUDIANTE] uniqueidentifier NOT NULL,
	[CANTIDAD_ENTREGADA] int NOT NULL,
	[COMPRA_RENTA] varchar(50) NULL,
	[MONTO_TOTAL] money NOT NULL
)
GO

CREATE TABLE [ESTUDIANTE]
(
	[CODIGO_ESTUDIANTE] uniqueidentifier NOT NULL,
	[NOMBRE_ESTUDIANTE] varchar(75) NOT NULL,
	[APELLIDOS_ESTUDIANTE] varchar(75) NOT NULL,
	[CODIGO_LIBRO] int NOT NULL,
	[PRESTAMOS_ATRASADOS] bit NULL,
	[TELEFONO] tinyint NOT NULL,
	[CORREO] varchar(50) NULL,
	[CARRERA] varchar(50) NULL
)
GO

CREATE TABLE [FACTURACION]
(
	[NUMERO_FACTURA] uniqueidentifier NOT NULL,
	[NOMBRE] varchar(50) NOT NULL,
	[APELLIDOS] varchar(50) NOT NULL,
	[DIRECCION] varchar(50) NOT NULL,
	[TELEFONO] int NOT NULL,
	[CORREO_ELECTRONICO] varchar(50) NOT NULL,
	[NOMBRE_PRODUCTO] varchar(50) NOT NULL,
	[CANTIDAD_COMPRADA] tinyint NOT NULL,
	[TOTAL_PAGADO] money NOT NULL
)
GO

CREATE TABLE [LIBRO_RENTA]
(
	[ID_LIBRO] uniqueidentifier NOT NULL,
	[TITULO] varchar(50) NOT NULL,
	[AUTOR] varchar(50) NOT NULL,
	[SINOPSIS] text NULL,
	[DISPONIBLE] bit NOT NULL,
	[RESPONSABLE_ACTUAL] int NULL,
	[TIEMPO_RESTANTE] time(7) NULL,
	[ULTIMO_PRESTAMO] date NULL
)
GO

CREATE TABLE [LIBRO_VENTA]
(
	[ID_LIBRO] uniqueidentifier NOT NULL,
	[TITULO] varchar(50) NOT NULL,
	[AUTOR] varchar(50) NOT NULL,
	[CANTIDAD_ALMACEN] tinyint NOT NULL,
	[SINOPSIS] varchar(50) NULL,
	[PRECIO] money NOT NULL,
	[FORMATO] varchar(50) NOT NULL
)
GO


ALTER TABLE [COMPRA_RENTA] 
 ADD CONSTRAINT [PK_COMPRA_RENTA]
	PRIMARY KEY CLUSTERED ([NUMERO_EVENTO] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_COMPRA_RENTA_ESTUDIANTE] 
 ON [COMPRA_RENTA] ([ID_ESTUDIANTE] ASC)
GO

ALTER TABLE [ESTUDIANTE] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([CODIGO_ESTUDIANTE] ASC)
GO

ALTER TABLE [FACTURACION] 
 ADD CONSTRAINT [PK_FATURACION]
	PRIMARY KEY CLUSTERED ([NUMERO_FACTURA] ASC)
GO

ALTER TABLE [LIBRO_RENTA] 
 ADD CONSTRAINT [PK_LIBRO_PRESTAMO]
	PRIMARY KEY CLUSTERED ([ID_LIBRO] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_LIBRO_RENTA_COMPRA_RENTA] 
 ON [LIBRO_RENTA] ([ID_LIBRO] ASC)
GO

ALTER TABLE [LIBRO_VENTA] 
 ADD CONSTRAINT [PK_LIBRO_VENTA]
	PRIMARY KEY CLUSTERED ([ID_LIBRO] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_LIBRO_VENTA_COMPRA_RENTA] 
 ON [LIBRO_VENTA] ([ID_LIBRO] ASC)
GO


ALTER TABLE [COMPRA_RENTA] ADD CONSTRAINT [FK_COMPRA_RENTA_ESTUDIANTE]
	FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [ESTUDIANTE] ([CODIGO_ESTUDIANTE]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LIBRO_RENTA] ADD CONSTRAINT [FK_LIBRO_RENTA_COMPRA_RENTA]
	FOREIGN KEY ([ID_LIBRO]) REFERENCES [COMPRA_RENTA] ([NUMERO_EVENTO]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LIBRO_VENTA] ADD CONSTRAINT [FK_LIBRO_VENTA_COMPRA_RENTA]
	FOREIGN KEY ([ID_LIBRO]) REFERENCES [COMPRA_RENTA] ([NUMERO_EVENTO]) ON DELETE No Action ON UPDATE No Action
GO
